# Generated by Django 5.1 on 2024-09-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Preparado', 'Preparado'), ('Pagado', 'Pagado')], default='Activo', max_length=10),
        ),
    ]
