# Generated by Django 5.1 on 2024-10-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pedido realizado', 'Pedido realizado'), ('Listo para entregar', 'Listo para entregar'), ('Pedido en mesa', 'Pedido en mesa'), ('Pagado', 'Pagado')], default='Pedido realizado', max_length=50),
        ),
    ]
