# Generated by Django 5.1 on 2024-09-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_categoria_id_alter_empleados_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamenu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
