# Generated by Django 5.1 on 2024-09-24 02:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_remove_pedidos_estado_pedidos_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='mesa',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado')], default='activo', max_length=10)),
                ('item_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.menuitem')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.mesa')),
            ],
            options={
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
